rob1:
  task_space_controller:
    type: coordinated_motion_controllers/RobotController
    joints:
      - rob1_joint1
      - rob1_joint2
      - rob1_joint3
      - rob1_joint4
      - rob1_joint5
      - rob1_joint6

    alpha: 0.1
    k_position: 10.0
    k_aiming: 10.0

    aiming_vec: [0.0, 1.0, 0.0]

    base_link: rob1_base_link
    eef_link: rob1_tool0

    setpoint_topic: setpoint

  coordinated_motion_controller:
    type: coordinated_motion_controllers/CoordinatedRobotController
    joints:
      - rob1_joint1
      - rob1_joint2
      - rob1_joint3
      - rob1_joint4
      - rob1_joint5
      - rob1_joint6

    alpha: 0.1
    k_position: 10.0
    k_aiming: 10.0

    aiming_vec: [0.0, 1.0, 0.0]

    positioner_link: positioner
    base_link: rob1_base_link
    eef_link: rob1_tool0

    positioner_topic: /positioner/joint_states
    setpoint_topic: setpoint
  

rob2:
  task_space_controller:
    type: coordinated_motion_controllers/RobotController
    joints:
      - rob2_joint1
      - rob2_joint2
      - rob2_joint3
      - rob2_joint4
      - rob2_joint5
      - rob2_joint6

    alpha: 0.1
    k_position: 10.0
    k_aiming: 10.0

    aiming_vec: [0.0, 1.0, 0.0]

    base_link: rob2_base_link
    eef_link: rob2_tool0

    setpoint_topic: setpoint

  coordinated_motion_controller:
    type: coordinated_motion_controllers/CoordinatedRobotController
    joints:
      - rob2_joint1
      - rob2_joint2
      - rob2_joint3
      - rob2_joint4
      - rob2_joint5
      - rob2_joint6

    alpha: 0.1
    k_position: 10.0
    k_aiming: 10.0

    aiming_vec: [0.0, 1.0, 0.0]

    positioner_link: positioner
    base_link: rob2_base_link
    eef_link: rob2_tool0

    positioner_topic: /positioner/joint_states
    setpoint_topic: setpoint


positioner:
  positioner_controller:
    type: coordinated_motion_controllers/PositionerController
    joints:
      - positioner_joint

    coordinated_controllers:
      - /rob1/coordinated_motion_controller
      - /rob2/coordinated_motion_controller
