// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <taskspace_controllers/utility.hpp>
#include <taskspace_controllers/setpoint.hpp>

#include <kdl/jntarrayvel.hpp>
#include <kdl/chainjnttojacsolver.hpp>
#include <kdl/chainfksolverpos_recursive.hpp>

#include <rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp>
#include <controller_interface/controller_interface.hpp>
#include <hardware_interface/types/hardware_interface_type_values.hpp>

#include <sensor_msgs/msg/joint_state.hpp>
#include <trajectory_msgs/msg/joint_trajectory_point.hpp>
#include <taskspace_control_msgs/msg/pose_twist_setpoint.hpp>
#include <coordinated_control_msgs/msg/positioner_setpoint.hpp>
#include <taskspace_control_msgs/srv/query_pose.hpp>

#include <realtime_tools/realtime_buffer.hpp>
#include <realtime_tools/realtime_publisher.hpp>

// auto-generated by generate_parameter_library
#include <coordinated_motion_controllers/coordinated_controller_base_parameters.hpp>

namespace coordinated_motion_controllers
{

class CoordinatedControllerBase
  : public controller_interface::ControllerInterface
{
public:
  using JointStateMsg = sensor_msgs::msg::JointState;
  using JointStateSub = rclcpp::Subscription<JointStateMsg>::SharedPtr;
  using QueryPoseSrv = taskspace_control_msgs::srv::QueryPose;
  using QueryPoseService = rclcpp::Service<QueryPoseSrv>::SharedPtr;

  virtual controller_interface::InterfaceConfiguration
  command_interface_configuration() const override;

  virtual controller_interface::InterfaceConfiguration
  state_interface_configuration() const override;

  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

protected:
  void synchronizeJointStates();
  void writeRobotCommand(const ctrl::VectorND& cmd);
  void writePositionerCommand(const ctrl::VectorND& cmd);

  // Callbacks
  void posJointStateCallback(const sensor_msgs::msg::JointState::SharedPtr msg);
  bool queryPoseService(
      const std::shared_ptr<taskspace_control_msgs::srv::QueryPose::Request>
          request,
      std::shared_ptr<taskspace_control_msgs::srv::QueryPose::Response>
          response);

protected:
  const std::vector<std::string> allowed_interface_types_ = {
    hardware_interface::HW_IF_POSITION,
    hardware_interface::HW_IF_VELOCITY,
  };

  // Joint configuration
  unsigned int n_robot_joints_, n_pos_joints_ = 0;
  // std::vector<hardware_interface::JointHandle> joint_handles_;
  std::string base_link_, eef_link_, positioner_link_;
  std::string setpoint_topic_;

  // Kinematics
  KDL::Chain robot_chain_, coordinated_chain_;
  std::unique_ptr<KDL::ChainFkSolverPos_recursive> coordinated_fk_solver_;
  KDL::JntArray upper_pos_limits_;
  KDL::JntArray lower_pos_limits_;

  // State feedback
  KDL::JntArrayVel robot_state_;

  // Positioner
  realtime_tools::RealtimeBuffer<KDL::JntArrayVel> positioner_state_;
  JointStateSub sub_positioner_joint_states_;
  std::unique_ptr<realtime_tools::RealtimePublisher<
      coordinated_control_msgs::msg::PositionerSetpoint>>
      positioner_setpoint_pub_;

  QueryPoseService query_pose_service_;
};

}  // namespace coordinated_motion_controllers
