// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

// KDL
#include <kdl/jntarray.hpp>
#include <kdl/jntarrayvel.hpp>
#include <kdl/chainjnttojacsolver.hpp>
#include <kdl/chainfksolverpos_recursive.hpp>

// ROS2 control
#include "controller_interface/controller_interface.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "joint_limits/joint_limits.hpp"

// ROS2 messages
#include "sensor_msgs/msg/joint_state.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"
#include "taskspace_control_msgs/msg/pose_twist_setpoint.hpp"
#include "coordinated_control_msgs/msg/positioner_setpoint.hpp"
#include "taskspace_control_msgs/srv/query_pose.hpp"

// Realtime tools
#include "realtime_tools/realtime_publisher.hpp"

// Taskspace controllers
#include "taskspace_controllers/utility.hpp"
#include "taskspace_controllers/setpoint.hpp"

// Coordination controllers
#include "coordinated_motion_controllers/positioner_state_interface/positioner_state_interface.hpp"

// auto-generated by generate_parameter_library
#include "coordinated_motion_controllers/coordinated_controller_base_parameters.hpp"

namespace coordinated_motion_controllers
{

class CoordinatedControllerBase
  : public controller_interface::ControllerInterface
{
public:
  virtual controller_interface::InterfaceConfiguration
  command_interface_configuration() const override;

  virtual controller_interface::InterfaceConfiguration
  state_interface_configuration() const override;

  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

  virtual controller_interface::CallbackReturn
  on_shutdown(const rclcpp_lifecycle::State& previous_state) override;

protected:
  // Hardware interface methods
  void read_state_from_hardware(KDL::JntArrayVel& state);
  void get_combined_state(KDL::JntArrayVel& state);
  void stop_motion();
  void write_robot_command(const KDL::JntArrayVel& cmd);
  void write_positioner_command(const ctrl::VectorND& cmd);

  // Utility functions
  bool check_manipulability(const KDL::Jacobian& jac);

  // Callbacks
  using QueryPose = taskspace_control_msgs::srv::QueryPose;
  virtual bool queryPoseServiceCb(const std::shared_ptr<QueryPose::Request> req,
                                  std::shared_ptr<QueryPose::Response> resp);

  std::shared_ptr<coordinated_controller_base::ParamListener> param_listener_;
  coordinated_controller_base::Params params_;

  const std::vector<std::string> allowed_interface_types_ = {
    hardware_interface::HW_IF_POSITION,
    hardware_interface::HW_IF_VELOCITY,
  };

  bool has_position_command_interface_ = false;
  bool has_velocity_command_interface_ = false;

  // Controller parameters
  std::vector<std::string> robot_joint_names_, positioner_joint_names_;
  unsigned int n_robot_joints_, n_pos_joints_ = 0;
  std::string base_link_, eef_link_, positioner_link_;

  // Kinematics
  KDL::Chain robot_chain_, coordinated_chain_;
  std::vector<joint_limits::JointLimits> joint_limits_;
  std::unique_ptr<KDL::ChainFkSolverPos_recursive> coordinated_fk_solver_;

  // State tracking
  KDL::JntArrayVel joint_state_;
  KDL::JntArrayVel last_commanded_;
  KDL::JntArrayVel last_reference_;

  using PosSetpointPublisher = realtime_tools::RealtimePublisher<
      coordinated_control_msgs::msg::PositionerSetpoint>;
  rclcpp::Publisher<coordinated_control_msgs::msg::PositionerSetpoint>::
      SharedPtr positioner_setpoint_pub_;
  std::unique_ptr<PosSetpointPublisher> realtime_setpoint_pub_;
  coordinated_control_msgs::msg::PositionerSetpoint positioner_setpoint_msg_;

  // Services
  rclcpp::Service<QueryPose>::SharedPtr query_pose_service_;

  // Positioner State Interface
  std::unique_ptr<PositionerStateInterface> pos_state_interface_;
};

}  // namespace coordinated_motion_controllers
