// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "coordinated_motion_controllers/coordinated_controller_base.hpp"
#include "coordinated_motion_controllers/positioner_objectives/positioner_objective_plugin.hpp"

#include <kdl/chainjnttojacsolver.hpp>

#include "taskspace_controllers/setpoint.hpp"
#include "task_priority_controllers/objectives/objective_plugin.hpp"
#include "realtime_tools/realtime_buffer.hpp"

#include "pluginlib/class_loader.hpp"

// auto-generated by generate_parameter_library
#include "coordinated_motion_controllers/coordinated_pose_controller_parameters.hpp"

namespace coordinated_motion_controllers
{
class PoseController : public virtual CoordinatedControllerBase
{
public:
  virtual controller_interface::CallbackReturn on_init() override;

  virtual controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;

  virtual controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

protected:
  using Setpoint = taskspace_controllers::PoseTwistSetpoint;

  // Parameters from ROS for pose_controller
  std::shared_ptr<coord_pose_controller::ParamListener> pose_param_listener_;
  coord_pose_controller::Params pose_params_;

  // -- Kinematics --
  std::unique_ptr<KDL::ChainJntToJacSolver> coordinated_jacobian_solver_;

  // -- Setpoint subscription --
  realtime_tools::RealtimeBuffer<Setpoint> setpoint_buffer_;
  rclcpp::Subscription<taskspace_control_msgs::msg::PoseTwistSetpoint>::
      SharedPtr setpoint_subscriber_;
  void setpointCallback(
      const taskspace_control_msgs::msg::PoseTwistSetpoint::SharedPtr msg);

  // redundancy resolution objective
  std::shared_ptr<task_priority_controllers::RRObjective> rr_objective_;
  std::unique_ptr<
      pluginlib::ClassLoader<task_priority_controllers::RRObjective>>
      rr_objective_loader_;

  // positioner objective
  std::shared_ptr<PositionerObjective> positioner_objective_;
  std::unique_ptr<pluginlib::ClassLoader<PositionerObjective>>
      positioner_objective_loader_;
};

}  // namespace coordinated_motion_controllers
