// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <kdl/jntarrayvel.hpp>

#include "controller_interface/controller_interface.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"

#include "coordinated_control_msgs/msg/positioner_setpoint.hpp"
#include "realtime_tools/realtime_buffer.hpp"

// auto-generated by generate_parameter_library
#include "coordinated_motion_controllers/positioner_controller_parameters.hpp"

namespace coordinated_motion_controllers
{

class CoordinatedRobotData
{
public:
  CoordinatedRobotData(const rclcpp_lifecycle::LifecycleNode::SharedPtr& node,
                       const std::string& controller_ns,
                       unsigned int n_pos_joints);

  realtime_tools::RealtimeBuffer<KDL::JntArray> rec_setpoint;
  std::atomic<bool> coord;

private:
  void setpointCallback(
      const coordinated_control_msgs::msg::PositionerSetpoint::SharedPtr msg);

private:
  rclcpp_lifecycle::LifecycleNode::SharedPtr node_;
  std::string controller_ns_;
  unsigned int n_pos_joints_;

  rclcpp::Subscription<coordinated_control_msgs::msg::PositionerSetpoint>::
      SharedPtr sub_rec_setpoint_;
};

class PositionerController : public controller_interface::ControllerInterface
{
public:
  controller_interface::InterfaceConfiguration
  command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration
  state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn
  on_configure(const rclcpp_lifecycle::State& previous_state) override;
  controller_interface::CallbackReturn
  on_activate(const rclcpp_lifecycle::State& previous_state) override;
  controller_interface::CallbackReturn
  on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

  controller_interface::return_type
  update(const rclcpp::Time& time, const rclcpp::Duration& period) override;

private:
  void read_state_from_hardware(KDL::JntArrayVel& state);
  void write_command(const KDL::JntArrayVel& cmd);

  const std::vector<std::string> allowed_interface_types_ = {
    hardware_interface::HW_IF_POSITION,
    hardware_interface::HW_IF_VELOCITY,
  };

  bool has_position_command_interface_ = false;
  bool has_velocity_command_interface_ = false;

  // Parameters
  std::shared_ptr<positioner_controller::ParamListener> param_listener_;
  positioner_controller::Params params_;

  unsigned int n_joints_;

  std::unordered_map<std::string, std::shared_ptr<CoordinatedRobotData>>
      robot_data_;

  // State tracking
  KDL::JntArrayVel joint_state_;
  KDL::JntArrayVel last_commanded_;
  KDL::JntArrayVel last_reference_;
};

}  // namespace coordinated_motion_controllers
