<?xml version="1.0"?>
<package format="3">
  <name>coordination_controllers</name>
  <version>0.1.2</version>
  <description>Coordinated control and redundancy resolution for multi-robot systems</description>
  <author email="arbogastaw@gmail.com">Alex Arbogast</author>
  <maintainer email="arbogastaw@gmail.com">Alex Arbogast</maintainer>
  <license>Apache2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>coordinated_motion_controllers</exec_depend>
  <exec_depend>coordinated_motion_examples</exec_depend>
  <exec_depend>coordinated_control_msgs</exec_depend>

  <export>
		<build_type>ament_cmake</build_type>
  </export>
</package>
