// Copyright 2024 Alex Arbogast
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include <kdl/jntarrayvel.hpp>

// Coordination controllers
#include "coordinated_motion_controllers/positioner_state_interface/positioner_state_interface.hpp"

// auto-generated by generate_parameter_library
#include "coordinated_motion_controllers/coordinated_controller_base_parameters.hpp"

namespace coordinated_motion_controllers
{
class PositionerStateInterface
{
public:
  PositionerStateInterface() = default;

  virtual bool init(std::shared_ptr<rclcpp_lifecycle::LifecycleNode> node,
                    const std::vector<std::string>& joint_names,
                    const coordinated_controller_base::Params& params) = 0;
  virtual bool read(KDL::JntArrayVel& state) = 0;

protected:
  std::vector<std::string> joint_names_;
  std::size_t n_joints_ = 0;
};

}  // namespace coordinated_motion_controllers
